### ISSUE TITLE
detection.txt

### ISSUE THREAD

**Issue by liuhengli** [pkdogcom/fddb-evaluate#1]
I can't found about generate the 'detection.txt' file of code.

**Comment by pkdogcom** [comment]
It should be generated by your detector, which is up to your implementation. The only reason I included this file is to give you an example of what format the docker script is expecting, which is explained in ReadMe.

**Comment by liuhengli** [comment]
sorry, this my mistake, I want to know the FDDB dataset is ellipse, and how to convert rectangle

**Comment by pkdogcom** [comment]
You don't need to convert. As long as you output your detection results as rectangle, the docker script (the official fddb evaluation script does the heavylifting actually) will take care of the rest and give the expected evaluation results.

**Comment by liuhengli** [comment]
Ok, thank you very much
